version: '3.1'

services:

  backend:
    build: .
    volumes:
      - .:/go/src/app
    command: sh run.sh
    ports:
      - 80:3000
    environment:
      - A=1

  db:
    image: cockroachdb/cockroach:v19.2.2
    command: start --insecure --advertise-addr 0.0.0.0
    environment:
      - name=roach1
      - hostname=roach1
      - net=roachnet
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - db_data:/cockroach/cockroach-data



volumes:
  db_data:
